report:
  settings:
    page:
      size: Letter
      orientation: P
      margins: 15
    style:
      font_family: 'Helvetica'
      font_size: 8
      font_color: [0, 0, 0]
  header:
    1:
      text:
        field: company_name
        margin: 10
        align: left
        style:
          font_size: 9
          font_weight: B
    2:
      text:
        field: company_rif
        margin: 10
        align: left
        style:
          font_size: 8
    3:
      image:
        filename: default-report-logo.png
        width: 8
        height: 8
        x: 15
        y: 15
    4:
      text:
        field: client_title
        align: right
        width: 150
        breakline: 0
        style:
          font_weight: B
    5:
      text:
        field: client_code
        align: right
    6:
      text:
        field: client_name
        align: right
    7:
      breakline:
  body:
    1:
      text:
        field: title
        align: center
        style:
          font_size: 8
          font_weight: B
    2:
      table:
        field: transactions
        heading:
          align: left
          style:
            font_weight: B
            bg_color: [220, 220, 220]
        totalization:
          label: Total
          align: right
          border: T
          style:
            font_weight: B
        columns:
          1:
            code:
              label: Codigo
              align: center
              width: 20
          2:
            name:
              label: Nombre
              align: left
              width: 85
          3:
            sacks:
              label: Sacos
              align: center
              width: 15
          4:
            sack_weight:
              label: Kg/Saco
              align: center
              width: 15
          5:
            amount:
              label: Cantidad
              unit: Kg
              totalize: true
              align: right
              width: 50
    3:
      breakline:
    4:
      text:
        label: Entrada
        width: 40
        breakline: 0
        style:
          font_weight: B
    5:
      text:
        label: Salida
        width: 40
        breakline: 0
        style:
          font_weight: B
    6:
      text:
        label: "Docum: "
        width: 18
        breakline: 0
        style:
          font_weight: B
    7:
      text:
        field: provider_document_number
        width: 20
        breakline: 0
    8:
      text:
        label: "Bruto:"
        width: 25
        breakline: 0
        style:
          font_weight: B
    9:
      text:
        field: gross_weight
        width: 25
    10:
      breakline:
    11:
      text:
        field: incoming_date
        width: 40
        breakline: 0
    12:
      text:
        field: outgoing_date
        width: 40
        breakline: 0
    13:
      text:
        label: "Placa: "
        width: 18
        breakline: 0
        style:
          font_weight: B
    14:
      text:
        field: license_plate
        width: 20
        breakline: 0 
    15:
      text:
        label: "Tara:"
        width: 25
        breakline: 0
        style:
          font_weight: B
    16:
      text:
        field: tare_weight
        width: 25
    17:
      text:
        field: incoming_weight
        width: 40
        breakline: 0
        
    18:
      text:
        field: outgoing_weight
        width: 40
        breakline: 0
    19:
      text:
        label: "Peso prov.:"
        width: 18
        breakline: 0
        style:
          font_weight: B
    20:
      text:
        field: provider_weight
        width: 20
        breakline: 0
    21:
      text:
        label: "Neto:"
        width: 25
        breakline: 0
        style:
          font_weight: B
    22:
      text:
        field: net_weight
        width: 25
    23:
      text:
        field: dif_label
        align: right
        width: 95
        breakline: 0
        style:
          font_weight: B
    24:
      text:
        field: dif
        align: right
        width: 20
        
    25:
      breakline:
    26:
      breakline:
    27:
      text:
        field: comment1
        align: left
        width: 30
    28:
      text:
        field: comment2
        align: left
        width: 30
    29:
      text:
        field: comment3
        align: left
        width: 30
    30:
      text:
        field: comment4
        align: left
        width: 30
    31:
      text:
        field: comment5
        align: left
        width: 30
    32:
      text:
        label: "Transp:"
        width: 11
        breakline: 0
        style:
          font_weight: B
    33:
      text:
        field: carrier
        width: 45
        breakline: 0
    34:
      text:
        label: "__________________________"
        width: 70
        breakline: 0
    35:
      text:
        label: "__________________________"
        width: 70
    36:
      text:
        label: "Despachador"
        width: 160
        breakline: 0
        style:
          font_weight: B
    37:
      text:
        field: driver_name
        width: -10
        
    38: 
      text:
        field: user_name
        breakline: 0
        width: 160
    39:
      text:
        field: driver_id
        width: -10
  footer:
    1:
      breakline:
